# SPDX-License-Identifier: CC-BY-4.0 OR GPL-3.0-or-later
# This file is part of Network Pro

blank_issues_enabled: false
contact_links:
  - name: Ask the community
    url: https://github.com/netwk-pro/netwk-pro.github.io/discussions/new
    about: Ask and discuss questions with other Network Pro Strategies community members.
  - name: Commonly asked questions
    url: https://stackoverflowteams.com/c/netwk-pro/questions
    about: Ask and answer common questions on Stack Overflow Teams.
